<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health/v1/health.proto

namespace Health\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>health.v1.CheckReply</code>
 */
class CheckReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string env = 3;</code>
     */
    protected $env = '';
    /**
     * Generated from protobuf field <code>string postgres = 4;</code>
     */
    protected $postgres = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type string $version
     *     @type string $env
     *     @type string $postgres
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Health\V1\Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string env = 3;</code>
     * @return string
     */
    public function getEnv()
    {
        return $this->env;
    }

    /**
     * Generated from protobuf field <code>string env = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEnv($var)
    {
        GPBUtil::checkString($var, True);
        $this->env = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postgres = 4;</code>
     * @return string
     */
    public function getPostgres()
    {
        return $this->postgres;
    }

    /**
     * Generated from protobuf field <code>string postgres = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPostgres($var)
    {
        GPBUtil::checkString($var, True);
        $this->postgres = $var;

        return $this;
    }

}

