<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openapi.v3.AdditionalPropertiesItem</code>
 */
class AdditionalPropertiesItem extends \Google\Protobuf\Internal\Message
{
    protected $oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Openapi\V3\SchemaOrReference $schema_or_reference
     *     @type bool $boolean
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SchemaOrReference schema_or_reference = 1;</code>
     * @return \Openapi\V3\SchemaOrReference|null
     */
    public function getSchemaOrReference()
    {
        return $this->readOneof(1);
    }

    public function hasSchemaOrReference()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SchemaOrReference schema_or_reference = 1;</code>
     * @param \Openapi\V3\SchemaOrReference $var
     * @return $this
     */
    public function setSchemaOrReference($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\SchemaOrReference::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean = 2;</code>
     * @return bool
     */
    public function getBoolean()
    {
        return $this->readOneof(2);
    }

    public function hasBoolean()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>bool boolean = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolean($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneof()
    {
        return $this->whichOneof("oneof");
    }

}

