<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openapi.v3.Any</code>
 */
class Any extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Any value = 1;</code>
     */
    protected $value = null;
    /**
     * Generated from protobuf field <code>string yaml = 2;</code>
     */
    protected $yaml = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any $value
     *     @type string $yaml
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any value = 1;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any value = 1;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string yaml = 2;</code>
     * @return string
     */
    public function getYaml()
    {
        return $this->yaml;
    }

    /**
     * Generated from protobuf field <code>string yaml = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setYaml($var)
    {
        GPBUtil::checkString($var, True);
        $this->yaml = $var;

        return $this;
    }

}

