<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openapi.v3.AnyOrExpression</code>
 */
class AnyOrExpression extends \Google\Protobuf\Internal\Message
{
    protected $oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Openapi\V3\Any $any
     *     @type \Openapi\V3\Expression $expression
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Any any = 1;</code>
     * @return \Openapi\V3\Any|null
     */
    public function getAny()
    {
        return $this->readOneof(1);
    }

    public function hasAny()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Any any = 1;</code>
     * @param \Openapi\V3\Any $var
     * @return $this
     */
    public function setAny($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Any::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Expression expression = 2;</code>
     * @return \Openapi\V3\Expression|null
     */
    public function getExpression()
    {
        return $this->readOneof(2);
    }

    public function hasExpression()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Expression expression = 2;</code>
     * @param \Openapi\V3\Expression $var
     * @return $this
     */
    public function setExpression($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Expression::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneof()
    {
        return $this->whichOneof("oneof");
    }

}

