<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Holds a set of reusable objects for different aspects of the OAS. All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object.
 *
 * Generated from protobuf message <code>openapi.v3.Components</code>
 */
class Components extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.openapi.v3.SchemasOrReferences schemas = 1;</code>
     */
    protected $schemas = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.ResponsesOrReferences responses = 2;</code>
     */
    protected $responses = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.ParametersOrReferences parameters = 3;</code>
     */
    protected $parameters = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.ExamplesOrReferences examples = 4;</code>
     */
    protected $examples = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.RequestBodiesOrReferences request_bodies = 5;</code>
     */
    protected $request_bodies = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 6;</code>
     */
    protected $headers = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.SecuritySchemesOrReferences security_schemes = 7;</code>
     */
    protected $security_schemes = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.LinksOrReferences links = 8;</code>
     */
    protected $links = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.CallbacksOrReferences callbacks = 9;</code>
     */
    protected $callbacks = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 10;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Openapi\V3\SchemasOrReferences $schemas
     *     @type \Openapi\V3\ResponsesOrReferences $responses
     *     @type \Openapi\V3\ParametersOrReferences $parameters
     *     @type \Openapi\V3\ExamplesOrReferences $examples
     *     @type \Openapi\V3\RequestBodiesOrReferences $request_bodies
     *     @type \Openapi\V3\HeadersOrReferences $headers
     *     @type \Openapi\V3\SecuritySchemesOrReferences $security_schemes
     *     @type \Openapi\V3\LinksOrReferences $links
     *     @type \Openapi\V3\CallbacksOrReferences $callbacks
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SchemasOrReferences schemas = 1;</code>
     * @return \Openapi\V3\SchemasOrReferences|null
     */
    public function getSchemas()
    {
        return $this->schemas;
    }

    public function hasSchemas()
    {
        return isset($this->schemas);
    }

    public function clearSchemas()
    {
        unset($this->schemas);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SchemasOrReferences schemas = 1;</code>
     * @param \Openapi\V3\SchemasOrReferences $var
     * @return $this
     */
    public function setSchemas($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\SchemasOrReferences::class);
        $this->schemas = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ResponsesOrReferences responses = 2;</code>
     * @return \Openapi\V3\ResponsesOrReferences|null
     */
    public function getResponses()
    {
        return $this->responses;
    }

    public function hasResponses()
    {
        return isset($this->responses);
    }

    public function clearResponses()
    {
        unset($this->responses);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ResponsesOrReferences responses = 2;</code>
     * @param \Openapi\V3\ResponsesOrReferences $var
     * @return $this
     */
    public function setResponses($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ResponsesOrReferences::class);
        $this->responses = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ParametersOrReferences parameters = 3;</code>
     * @return \Openapi\V3\ParametersOrReferences|null
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    public function hasParameters()
    {
        return isset($this->parameters);
    }

    public function clearParameters()
    {
        unset($this->parameters);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ParametersOrReferences parameters = 3;</code>
     * @param \Openapi\V3\ParametersOrReferences $var
     * @return $this
     */
    public function setParameters($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ParametersOrReferences::class);
        $this->parameters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExamplesOrReferences examples = 4;</code>
     * @return \Openapi\V3\ExamplesOrReferences|null
     */
    public function getExamples()
    {
        return $this->examples;
    }

    public function hasExamples()
    {
        return isset($this->examples);
    }

    public function clearExamples()
    {
        unset($this->examples);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExamplesOrReferences examples = 4;</code>
     * @param \Openapi\V3\ExamplesOrReferences $var
     * @return $this
     */
    public function setExamples($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ExamplesOrReferences::class);
        $this->examples = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.RequestBodiesOrReferences request_bodies = 5;</code>
     * @return \Openapi\V3\RequestBodiesOrReferences|null
     */
    public function getRequestBodies()
    {
        return $this->request_bodies;
    }

    public function hasRequestBodies()
    {
        return isset($this->request_bodies);
    }

    public function clearRequestBodies()
    {
        unset($this->request_bodies);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.RequestBodiesOrReferences request_bodies = 5;</code>
     * @param \Openapi\V3\RequestBodiesOrReferences $var
     * @return $this
     */
    public function setRequestBodies($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\RequestBodiesOrReferences::class);
        $this->request_bodies = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 6;</code>
     * @return \Openapi\V3\HeadersOrReferences|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 6;</code>
     * @param \Openapi\V3\HeadersOrReferences $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\HeadersOrReferences::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SecuritySchemesOrReferences security_schemes = 7;</code>
     * @return \Openapi\V3\SecuritySchemesOrReferences|null
     */
    public function getSecuritySchemes()
    {
        return $this->security_schemes;
    }

    public function hasSecuritySchemes()
    {
        return isset($this->security_schemes);
    }

    public function clearSecuritySchemes()
    {
        unset($this->security_schemes);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SecuritySchemesOrReferences security_schemes = 7;</code>
     * @param \Openapi\V3\SecuritySchemesOrReferences $var
     * @return $this
     */
    public function setSecuritySchemes($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\SecuritySchemesOrReferences::class);
        $this->security_schemes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.LinksOrReferences links = 8;</code>
     * @return \Openapi\V3\LinksOrReferences|null
     */
    public function getLinks()
    {
        return $this->links;
    }

    public function hasLinks()
    {
        return isset($this->links);
    }

    public function clearLinks()
    {
        unset($this->links);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.LinksOrReferences links = 8;</code>
     * @param \Openapi\V3\LinksOrReferences $var
     * @return $this
     */
    public function setLinks($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\LinksOrReferences::class);
        $this->links = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.CallbacksOrReferences callbacks = 9;</code>
     * @return \Openapi\V3\CallbacksOrReferences|null
     */
    public function getCallbacks()
    {
        return $this->callbacks;
    }

    public function hasCallbacks()
    {
        return isset($this->callbacks);
    }

    public function clearCallbacks()
    {
        unset($this->callbacks);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.CallbacksOrReferences callbacks = 9;</code>
     * @param \Openapi\V3\CallbacksOrReferences $var
     * @return $this
     */
    public function setCallbacks($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\CallbacksOrReferences::class);
        $this->callbacks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 10;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

