<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openapi.v3.DefaultType</code>
 */
class DefaultType extends \Google\Protobuf\Internal\Message
{
    protected $oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $number
     *     @type bool $boolean
     *     @type string $string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double number = 1;</code>
     * @return float
     */
    public function getNumber()
    {
        return $this->readOneof(1);
    }

    public function hasNumber()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>double number = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean = 2;</code>
     * @return bool
     */
    public function getBoolean()
    {
        return $this->readOneof(2);
    }

    public function hasBoolean()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>bool boolean = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolean($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string = 3;</code>
     * @return string
     */
    public function getString()
    {
        return $this->readOneof(3);
    }

    public function hasString()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string string = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneof()
    {
        return $this->whichOneof("oneof");
    }

}

