<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * When request bodies or response payloads may be one of a number of different schemas, a `discriminator` object can be used to aid in serialization, deserialization, and validation.  The discriminator is a specific object in a schema which is used to inform the consumer of the specification of an alternative schema based on the value associated with it.  When using the discriminator, _inline_ schemas will not be considered.
 *
 * Generated from protobuf message <code>openapi.v3.Discriminator</code>
 */
class Discriminator extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string property_name = 1;</code>
     */
    protected $property_name = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.Strings mapping = 2;</code>
     */
    protected $mapping = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 3;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $property_name
     *     @type \Openapi\V3\Strings $mapping
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string property_name = 1;</code>
     * @return string
     */
    public function getPropertyName()
    {
        return $this->property_name;
    }

    /**
     * Generated from protobuf field <code>string property_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPropertyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->property_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Strings mapping = 2;</code>
     * @return \Openapi\V3\Strings|null
     */
    public function getMapping()
    {
        return $this->mapping;
    }

    public function hasMapping()
    {
        return isset($this->mapping);
    }

    public function clearMapping()
    {
        unset($this->mapping);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Strings mapping = 2;</code>
     * @param \Openapi\V3\Strings $var
     * @return $this
     */
    public function setMapping($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Strings::class);
        $this->mapping = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 3;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

