<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openapi.v3.Document</code>
 */
class Document extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string openapi = 1;</code>
     */
    protected $openapi = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.Info info = 2;</code>
     */
    protected $info = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 3;</code>
     */
    private $servers;
    /**
     * Generated from protobuf field <code>.openapi.v3.Paths paths = 4;</code>
     */
    protected $paths = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Components components = 5;</code>
     */
    protected $components = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SecurityRequirement security = 6;</code>
     */
    private $security;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Tag tags = 7;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 8;</code>
     */
    protected $external_docs = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 9;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $openapi
     *     @type \Openapi\V3\Info $info
     *     @type array<\Openapi\V3\Server>|\Google\Protobuf\Internal\RepeatedField $servers
     *     @type \Openapi\V3\Paths $paths
     *     @type \Openapi\V3\Components $components
     *     @type array<\Openapi\V3\SecurityRequirement>|\Google\Protobuf\Internal\RepeatedField $security
     *     @type array<\Openapi\V3\Tag>|\Google\Protobuf\Internal\RepeatedField $tags
     *     @type \Openapi\V3\ExternalDocs $external_docs
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string openapi = 1;</code>
     * @return string
     */
    public function getOpenapi()
    {
        return $this->openapi;
    }

    /**
     * Generated from protobuf field <code>string openapi = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenapi($var)
    {
        GPBUtil::checkString($var, True);
        $this->openapi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Info info = 2;</code>
     * @return \Openapi\V3\Info|null
     */
    public function getInfo()
    {
        return $this->info;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Info info = 2;</code>
     * @param \Openapi\V3\Info $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Info::class);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServers()
    {
        return $this->servers;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 3;</code>
     * @param array<\Openapi\V3\Server>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\Server::class);
        $this->servers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Paths paths = 4;</code>
     * @return \Openapi\V3\Paths|null
     */
    public function getPaths()
    {
        return $this->paths;
    }

    public function hasPaths()
    {
        return isset($this->paths);
    }

    public function clearPaths()
    {
        unset($this->paths);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Paths paths = 4;</code>
     * @param \Openapi\V3\Paths $var
     * @return $this
     */
    public function setPaths($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Paths::class);
        $this->paths = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Components components = 5;</code>
     * @return \Openapi\V3\Components|null
     */
    public function getComponents()
    {
        return $this->components;
    }

    public function hasComponents()
    {
        return isset($this->components);
    }

    public function clearComponents()
    {
        unset($this->components);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Components components = 5;</code>
     * @param \Openapi\V3\Components $var
     * @return $this
     */
    public function setComponents($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Components::class);
        $this->components = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SecurityRequirement security = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SecurityRequirement security = 6;</code>
     * @param array<\Openapi\V3\SecurityRequirement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecurity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\SecurityRequirement::class);
        $this->security = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Tag tags = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Tag tags = 7;</code>
     * @param array<\Openapi\V3\Tag>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\Tag::class);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 8;</code>
     * @return \Openapi\V3\ExternalDocs|null
     */
    public function getExternalDocs()
    {
        return $this->external_docs;
    }

    public function hasExternalDocs()
    {
        return isset($this->external_docs);
    }

    public function clearExternalDocs()
    {
        unset($this->external_docs);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 8;</code>
     * @param \Openapi\V3\ExternalDocs $var
     * @return $this
     */
    public function setExternalDocs($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ExternalDocs::class);
        $this->external_docs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 9;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

