<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A single encoding definition applied to a single schema property.
 *
 * Generated from protobuf message <code>openapi.v3.Encoding</code>
 */
class Encoding extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string content_type = 1;</code>
     */
    protected $content_type = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 2;</code>
     */
    protected $headers = null;
    /**
     * Generated from protobuf field <code>string style = 3;</code>
     */
    protected $style = '';
    /**
     * Generated from protobuf field <code>bool explode = 4;</code>
     */
    protected $explode = false;
    /**
     * Generated from protobuf field <code>bool allow_reserved = 5;</code>
     */
    protected $allow_reserved = false;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 6;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $content_type
     *     @type \Openapi\V3\HeadersOrReferences $headers
     *     @type string $style
     *     @type bool $explode
     *     @type bool $allow_reserved
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string content_type = 1;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>string content_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 2;</code>
     * @return \Openapi\V3\HeadersOrReferences|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 2;</code>
     * @param \Openapi\V3\HeadersOrReferences $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\HeadersOrReferences::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string style = 3;</code>
     * @return string
     */
    public function getStyle()
    {
        return $this->style;
    }

    /**
     * Generated from protobuf field <code>string style = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStyle($var)
    {
        GPBUtil::checkString($var, True);
        $this->style = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool explode = 4;</code>
     * @return bool
     */
    public function getExplode()
    {
        return $this->explode;
    }

    /**
     * Generated from protobuf field <code>bool explode = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setExplode($var)
    {
        GPBUtil::checkBool($var);
        $this->explode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allow_reserved = 5;</code>
     * @return bool
     */
    public function getAllowReserved()
    {
        return $this->allow_reserved;
    }

    /**
     * Generated from protobuf field <code>bool allow_reserved = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowReserved($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_reserved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 6;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

