<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openapi.v3.ItemsItem</code>
 */
class ItemsItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference schema_or_reference = 1;</code>
     */
    private $schema_or_reference;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $schema_or_reference
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference schema_or_reference = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSchemaOrReference()
    {
        return $this->schema_or_reference;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference schema_or_reference = 1;</code>
     * @param array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSchemaOrReference($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\SchemaOrReference::class);
        $this->schema_or_reference = $arr;

        return $this;
    }

}

