<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The `Link object` represents a possible design-time link for a response. The presence of a link does not guarantee the caller's ability to successfully invoke it, rather it provides a known relationship and traversal mechanism between responses and other operations.  Unlike _dynamic_ links (i.e. links provided **in** the response payload), the OAS linking mechanism does not require link information in the runtime response.  For computing links, and providing instructions to execute them, a runtime expression is used for accessing values in an operation and using them as parameters while invoking the linked operation.
 *
 * Generated from protobuf message <code>openapi.v3.Link</code>
 */
class Link extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string operation_ref = 1;</code>
     */
    protected $operation_ref = '';
    /**
     * Generated from protobuf field <code>string operation_id = 2;</code>
     */
    protected $operation_id = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.AnyOrExpression parameters = 3;</code>
     */
    protected $parameters = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.AnyOrExpression request_body = 4;</code>
     */
    protected $request_body = null;
    /**
     * Generated from protobuf field <code>string description = 5;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.Server server = 6;</code>
     */
    protected $server = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 7;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $operation_ref
     *     @type string $operation_id
     *     @type \Openapi\V3\AnyOrExpression $parameters
     *     @type \Openapi\V3\AnyOrExpression $request_body
     *     @type string $description
     *     @type \Openapi\V3\Server $server
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string operation_ref = 1;</code>
     * @return string
     */
    public function getOperationRef()
    {
        return $this->operation_ref;
    }

    /**
     * Generated from protobuf field <code>string operation_ref = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_ref = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 2;</code>
     * @return string
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.AnyOrExpression parameters = 3;</code>
     * @return \Openapi\V3\AnyOrExpression|null
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    public function hasParameters()
    {
        return isset($this->parameters);
    }

    public function clearParameters()
    {
        unset($this->parameters);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.AnyOrExpression parameters = 3;</code>
     * @param \Openapi\V3\AnyOrExpression $var
     * @return $this
     */
    public function setParameters($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\AnyOrExpression::class);
        $this->parameters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.AnyOrExpression request_body = 4;</code>
     * @return \Openapi\V3\AnyOrExpression|null
     */
    public function getRequestBody()
    {
        return $this->request_body;
    }

    public function hasRequestBody()
    {
        return isset($this->request_body);
    }

    public function clearRequestBody()
    {
        unset($this->request_body);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.AnyOrExpression request_body = 4;</code>
     * @param \Openapi\V3\AnyOrExpression $var
     * @return $this
     */
    public function setRequestBody($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\AnyOrExpression::class);
        $this->request_body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Server server = 6;</code>
     * @return \Openapi\V3\Server|null
     */
    public function getServer()
    {
        return $this->server;
    }

    public function hasServer()
    {
        return isset($this->server);
    }

    public function clearServer()
    {
        unset($this->server);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Server server = 6;</code>
     * @param \Openapi\V3\Server $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Server::class);
        $this->server = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 7;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

