<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Each Media Type Object provides schema and examples for the media type identified by its key.
 *
 * Generated from protobuf message <code>openapi.v3.MediaType</code>
 */
class MediaType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.openapi.v3.SchemaOrReference schema = 1;</code>
     */
    protected $schema = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Any example = 2;</code>
     */
    protected $example = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.ExamplesOrReferences examples = 3;</code>
     */
    protected $examples = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Encodings encoding = 4;</code>
     */
    protected $encoding = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Openapi\V3\SchemaOrReference $schema
     *     @type \Openapi\V3\Any $example
     *     @type \Openapi\V3\ExamplesOrReferences $examples
     *     @type \Openapi\V3\Encodings $encoding
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SchemaOrReference schema = 1;</code>
     * @return \Openapi\V3\SchemaOrReference|null
     */
    public function getSchema()
    {
        return $this->schema;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.SchemaOrReference schema = 1;</code>
     * @param \Openapi\V3\SchemaOrReference $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\SchemaOrReference::class);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Any example = 2;</code>
     * @return \Openapi\V3\Any|null
     */
    public function getExample()
    {
        return $this->example;
    }

    public function hasExample()
    {
        return isset($this->example);
    }

    public function clearExample()
    {
        unset($this->example);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Any example = 2;</code>
     * @param \Openapi\V3\Any $var
     * @return $this
     */
    public function setExample($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Any::class);
        $this->example = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExamplesOrReferences examples = 3;</code>
     * @return \Openapi\V3\ExamplesOrReferences|null
     */
    public function getExamples()
    {
        return $this->examples;
    }

    public function hasExamples()
    {
        return isset($this->examples);
    }

    public function clearExamples()
    {
        unset($this->examples);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExamplesOrReferences examples = 3;</code>
     * @param \Openapi\V3\ExamplesOrReferences $var
     * @return $this
     */
    public function setExamples($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ExamplesOrReferences::class);
        $this->examples = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Encodings encoding = 4;</code>
     * @return \Openapi\V3\Encodings|null
     */
    public function getEncoding()
    {
        return $this->encoding;
    }

    public function hasEncoding()
    {
        return isset($this->encoding);
    }

    public function clearEncoding()
    {
        unset($this->encoding);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Encodings encoding = 4;</code>
     * @param \Openapi\V3\Encodings $var
     * @return $this
     */
    public function setEncoding($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Encodings::class);
        $this->encoding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

