<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Configuration details for a supported OAuth Flow
 *
 * Generated from protobuf message <code>openapi.v3.OauthFlow</code>
 */
class OauthFlow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string authorization_url = 1;</code>
     */
    protected $authorization_url = '';
    /**
     * Generated from protobuf field <code>string token_url = 2;</code>
     */
    protected $token_url = '';
    /**
     * Generated from protobuf field <code>string refresh_url = 3;</code>
     */
    protected $refresh_url = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.Strings scopes = 4;</code>
     */
    protected $scopes = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $authorization_url
     *     @type string $token_url
     *     @type string $refresh_url
     *     @type \Openapi\V3\Strings $scopes
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string authorization_url = 1;</code>
     * @return string
     */
    public function getAuthorizationUrl()
    {
        return $this->authorization_url;
    }

    /**
     * Generated from protobuf field <code>string authorization_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorizationUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->authorization_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_url = 2;</code>
     * @return string
     */
    public function getTokenUrl()
    {
        return $this->token_url;
    }

    /**
     * Generated from protobuf field <code>string token_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string refresh_url = 3;</code>
     * @return string
     */
    public function getRefreshUrl()
    {
        return $this->refresh_url;
    }

    /**
     * Generated from protobuf field <code>string refresh_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->refresh_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Strings scopes = 4;</code>
     * @return \Openapi\V3\Strings|null
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    public function hasScopes()
    {
        return isset($this->scopes);
    }

    public function clearScopes()
    {
        unset($this->scopes);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Strings scopes = 4;</code>
     * @param \Openapi\V3\Strings $var
     * @return $this
     */
    public function setScopes($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Strings::class);
        $this->scopes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

