<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Allows configuration of the supported OAuth Flows.
 *
 * Generated from protobuf message <code>openapi.v3.OauthFlows</code>
 */
class OauthFlows extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow implicit = 1;</code>
     */
    protected $implicit = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow password = 2;</code>
     */
    protected $password = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow client_credentials = 3;</code>
     */
    protected $client_credentials = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow authorization_code = 4;</code>
     */
    protected $authorization_code = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Openapi\V3\OauthFlow $implicit
     *     @type \Openapi\V3\OauthFlow $password
     *     @type \Openapi\V3\OauthFlow $client_credentials
     *     @type \Openapi\V3\OauthFlow $authorization_code
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow implicit = 1;</code>
     * @return \Openapi\V3\OauthFlow|null
     */
    public function getImplicit()
    {
        return $this->implicit;
    }

    public function hasImplicit()
    {
        return isset($this->implicit);
    }

    public function clearImplicit()
    {
        unset($this->implicit);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow implicit = 1;</code>
     * @param \Openapi\V3\OauthFlow $var
     * @return $this
     */
    public function setImplicit($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\OauthFlow::class);
        $this->implicit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow password = 2;</code>
     * @return \Openapi\V3\OauthFlow|null
     */
    public function getPassword()
    {
        return $this->password;
    }

    public function hasPassword()
    {
        return isset($this->password);
    }

    public function clearPassword()
    {
        unset($this->password);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow password = 2;</code>
     * @param \Openapi\V3\OauthFlow $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\OauthFlow::class);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow client_credentials = 3;</code>
     * @return \Openapi\V3\OauthFlow|null
     */
    public function getClientCredentials()
    {
        return $this->client_credentials;
    }

    public function hasClientCredentials()
    {
        return isset($this->client_credentials);
    }

    public function clearClientCredentials()
    {
        unset($this->client_credentials);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow client_credentials = 3;</code>
     * @param \Openapi\V3\OauthFlow $var
     * @return $this
     */
    public function setClientCredentials($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\OauthFlow::class);
        $this->client_credentials = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow authorization_code = 4;</code>
     * @return \Openapi\V3\OauthFlow|null
     */
    public function getAuthorizationCode()
    {
        return $this->authorization_code;
    }

    public function hasAuthorizationCode()
    {
        return isset($this->authorization_code);
    }

    public function clearAuthorizationCode()
    {
        unset($this->authorization_code);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlow authorization_code = 4;</code>
     * @param \Openapi\V3\OauthFlow $var
     * @return $this
     */
    public function setAuthorizationCode($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\OauthFlow::class);
        $this->authorization_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

