<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a single API operation on a path.
 *
 * Generated from protobuf message <code>openapi.v3.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     */
    protected $summary = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 4;</code>
     */
    protected $external_docs = null;
    /**
     * Generated from protobuf field <code>string operation_id = 5;</code>
     */
    protected $operation_id = '';
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.ParameterOrReference parameters = 6;</code>
     */
    private $parameters;
    /**
     * Generated from protobuf field <code>.openapi.v3.RequestBodyOrReference request_body = 7;</code>
     */
    protected $request_body = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Responses responses = 8;</code>
     */
    protected $responses = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.CallbacksOrReferences callbacks = 9;</code>
     */
    protected $callbacks = null;
    /**
     * Generated from protobuf field <code>bool deprecated = 10;</code>
     */
    protected $deprecated = false;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SecurityRequirement security = 11;</code>
     */
    private $security;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 12;</code>
     */
    private $servers;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 13;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $tags
     *     @type string $summary
     *     @type string $description
     *     @type \Openapi\V3\ExternalDocs $external_docs
     *     @type string $operation_id
     *     @type array<\Openapi\V3\ParameterOrReference>|\Google\Protobuf\Internal\RepeatedField $parameters
     *     @type \Openapi\V3\RequestBodyOrReference $request_body
     *     @type \Openapi\V3\Responses $responses
     *     @type \Openapi\V3\CallbacksOrReferences $callbacks
     *     @type bool $deprecated
     *     @type array<\Openapi\V3\SecurityRequirement>|\Google\Protobuf\Internal\RepeatedField $security
     *     @type array<\Openapi\V3\Server>|\Google\Protobuf\Internal\RepeatedField $servers
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 4;</code>
     * @return \Openapi\V3\ExternalDocs|null
     */
    public function getExternalDocs()
    {
        return $this->external_docs;
    }

    public function hasExternalDocs()
    {
        return isset($this->external_docs);
    }

    public function clearExternalDocs()
    {
        unset($this->external_docs);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 4;</code>
     * @param \Openapi\V3\ExternalDocs $var
     * @return $this
     */
    public function setExternalDocs($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ExternalDocs::class);
        $this->external_docs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 5;</code>
     * @return string
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.ParameterOrReference parameters = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.ParameterOrReference parameters = 6;</code>
     * @param array<\Openapi\V3\ParameterOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\ParameterOrReference::class);
        $this->parameters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.RequestBodyOrReference request_body = 7;</code>
     * @return \Openapi\V3\RequestBodyOrReference|null
     */
    public function getRequestBody()
    {
        return $this->request_body;
    }

    public function hasRequestBody()
    {
        return isset($this->request_body);
    }

    public function clearRequestBody()
    {
        unset($this->request_body);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.RequestBodyOrReference request_body = 7;</code>
     * @param \Openapi\V3\RequestBodyOrReference $var
     * @return $this
     */
    public function setRequestBody($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\RequestBodyOrReference::class);
        $this->request_body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Responses responses = 8;</code>
     * @return \Openapi\V3\Responses|null
     */
    public function getResponses()
    {
        return $this->responses;
    }

    public function hasResponses()
    {
        return isset($this->responses);
    }

    public function clearResponses()
    {
        unset($this->responses);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Responses responses = 8;</code>
     * @param \Openapi\V3\Responses $var
     * @return $this
     */
    public function setResponses($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Responses::class);
        $this->responses = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.CallbacksOrReferences callbacks = 9;</code>
     * @return \Openapi\V3\CallbacksOrReferences|null
     */
    public function getCallbacks()
    {
        return $this->callbacks;
    }

    public function hasCallbacks()
    {
        return isset($this->callbacks);
    }

    public function clearCallbacks()
    {
        unset($this->callbacks);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.CallbacksOrReferences callbacks = 9;</code>
     * @param \Openapi\V3\CallbacksOrReferences $var
     * @return $this
     */
    public function setCallbacks($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\CallbacksOrReferences::class);
        $this->callbacks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deprecated = 10;</code>
     * @return bool
     */
    public function getDeprecated()
    {
        return $this->deprecated;
    }

    /**
     * Generated from protobuf field <code>bool deprecated = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeprecated($var)
    {
        GPBUtil::checkBool($var);
        $this->deprecated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SecurityRequirement security = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SecurityRequirement security = 11;</code>
     * @param array<\Openapi\V3\SecurityRequirement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecurity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\SecurityRequirement::class);
        $this->security = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServers()
    {
        return $this->servers;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 12;</code>
     * @param array<\Openapi\V3\Server>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\Server::class);
        $this->servers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 13;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

