<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes the operations available on a single path. A Path Item MAY be empty, due to ACL constraints. The path itself is still exposed to the documentation viewer but they will not know which operations and parameters are available.
 *
 * Generated from protobuf message <code>openapi.v3.PathItem</code>
 */
class PathItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string _ref = 1;</code>
     */
    protected $_ref = '';
    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     */
    protected $summary = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation get = 4;</code>
     */
    protected $get = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation put = 5;</code>
     */
    protected $put = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation post = 6;</code>
     */
    protected $post = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation delete = 7;</code>
     */
    protected $delete = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation options = 8;</code>
     */
    protected $options = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation head = 9;</code>
     */
    protected $head = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation patch = 10;</code>
     */
    protected $patch = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Operation trace = 11;</code>
     */
    protected $trace = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 12;</code>
     */
    private $servers;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.ParameterOrReference parameters = 13;</code>
     */
    private $parameters;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 14;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $_ref
     *     @type string $summary
     *     @type string $description
     *     @type \Openapi\V3\Operation $get
     *     @type \Openapi\V3\Operation $put
     *     @type \Openapi\V3\Operation $post
     *     @type \Openapi\V3\Operation $delete
     *     @type \Openapi\V3\Operation $options
     *     @type \Openapi\V3\Operation $head
     *     @type \Openapi\V3\Operation $patch
     *     @type \Openapi\V3\Operation $trace
     *     @type array<\Openapi\V3\Server>|\Google\Protobuf\Internal\RepeatedField $servers
     *     @type array<\Openapi\V3\ParameterOrReference>|\Google\Protobuf\Internal\RepeatedField $parameters
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string _ref = 1;</code>
     * @return string
     */
    public function getRef()
    {
        return $this->_ref;
    }

    /**
     * Generated from protobuf field <code>string _ref = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->_ref = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>string summary = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation get = 4;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getGet()
    {
        return $this->get;
    }

    public function hasGet()
    {
        return isset($this->get);
    }

    public function clearGet()
    {
        unset($this->get);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation get = 4;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setGet($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->get = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation put = 5;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getPut()
    {
        return $this->put;
    }

    public function hasPut()
    {
        return isset($this->put);
    }

    public function clearPut()
    {
        unset($this->put);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation put = 5;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setPut($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->put = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation post = 6;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getPost()
    {
        return $this->post;
    }

    public function hasPost()
    {
        return isset($this->post);
    }

    public function clearPost()
    {
        unset($this->post);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation post = 6;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setPost($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->post = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation delete = 7;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getDelete()
    {
        return $this->delete;
    }

    public function hasDelete()
    {
        return isset($this->delete);
    }

    public function clearDelete()
    {
        unset($this->delete);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation delete = 7;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setDelete($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->delete = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation options = 8;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation options = 8;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation head = 9;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getHead()
    {
        return $this->head;
    }

    public function hasHead()
    {
        return isset($this->head);
    }

    public function clearHead()
    {
        unset($this->head);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation head = 9;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setHead($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->head = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation patch = 10;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getPatch()
    {
        return $this->patch;
    }

    public function hasPatch()
    {
        return isset($this->patch);
    }

    public function clearPatch()
    {
        unset($this->patch);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation patch = 10;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setPatch($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->patch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation trace = 11;</code>
     * @return \Openapi\V3\Operation|null
     */
    public function getTrace()
    {
        return $this->trace;
    }

    public function hasTrace()
    {
        return isset($this->trace);
    }

    public function clearTrace()
    {
        unset($this->trace);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Operation trace = 11;</code>
     * @param \Openapi\V3\Operation $var
     * @return $this
     */
    public function setTrace($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Operation::class);
        $this->trace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServers()
    {
        return $this->servers;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Server servers = 12;</code>
     * @param array<\Openapi\V3\Server>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\Server::class);
        $this->servers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.ParameterOrReference parameters = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.ParameterOrReference parameters = 13;</code>
     * @param array<\Openapi\V3\ParameterOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\ParameterOrReference::class);
        $this->parameters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 14;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

