<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a single response from an API Operation, including design-time, static  `links` to operations based on the response.
 *
 * Generated from protobuf message <code>openapi.v3.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 2;</code>
     */
    protected $headers = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.MediaTypes content = 3;</code>
     */
    protected $content = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.LinksOrReferences links = 4;</code>
     */
    protected $links = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type \Openapi\V3\HeadersOrReferences $headers
     *     @type \Openapi\V3\MediaTypes $content
     *     @type \Openapi\V3\LinksOrReferences $links
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 2;</code>
     * @return \Openapi\V3\HeadersOrReferences|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.HeadersOrReferences headers = 2;</code>
     * @param \Openapi\V3\HeadersOrReferences $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\HeadersOrReferences::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.MediaTypes content = 3;</code>
     * @return \Openapi\V3\MediaTypes|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.MediaTypes content = 3;</code>
     * @param \Openapi\V3\MediaTypes $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\MediaTypes::class);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.LinksOrReferences links = 4;</code>
     * @return \Openapi\V3\LinksOrReferences|null
     */
    public function getLinks()
    {
        return $this->links;
    }

    public function hasLinks()
    {
        return isset($this->links);
    }

    public function clearLinks()
    {
        unset($this->links);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.LinksOrReferences links = 4;</code>
     * @param \Openapi\V3\LinksOrReferences $var
     * @return $this
     */
    public function setLinks($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\LinksOrReferences::class);
        $this->links = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 5;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

