<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A container for the expected responses of an operation. The container maps a HTTP response code to the expected response.  The documentation is not necessarily expected to cover all possible HTTP response codes because they may not be known in advance. However, documentation is expected to cover a successful operation response and any known errors.  The `default` MAY be used as a default response object for all HTTP codes  that are not covered individually by the specification.  The `Responses Object` MUST contain at least one response code, and it  SHOULD be the response for a successful operation call.
 *
 * Generated from protobuf message <code>openapi.v3.Responses</code>
 */
class Responses extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.openapi.v3.ResponseOrReference default = 1;</code>
     */
    protected $default = null;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedResponseOrReference response_or_reference = 2;</code>
     */
    private $response_or_reference;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 3;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Openapi\V3\ResponseOrReference $default
     *     @type array<\Openapi\V3\NamedResponseOrReference>|\Google\Protobuf\Internal\RepeatedField $response_or_reference
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ResponseOrReference default = 1;</code>
     * @return \Openapi\V3\ResponseOrReference|null
     */
    public function getDefault()
    {
        return $this->default;
    }

    public function hasDefault()
    {
        return isset($this->default);
    }

    public function clearDefault()
    {
        unset($this->default);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ResponseOrReference default = 1;</code>
     * @param \Openapi\V3\ResponseOrReference $var
     * @return $this
     */
    public function setDefault($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ResponseOrReference::class);
        $this->default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedResponseOrReference response_or_reference = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponseOrReference()
    {
        return $this->response_or_reference;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedResponseOrReference response_or_reference = 2;</code>
     * @param array<\Openapi\V3\NamedResponseOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponseOrReference($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedResponseOrReference::class);
        $this->response_or_reference = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 3;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

