<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is an extended subset of the JSON Schema Specification Wright Draft 00.  For more information about the properties, see JSON Schema Core and JSON Schema Validation. Unless stated otherwise, the property definitions follow the JSON Schema.
 *
 * Generated from protobuf message <code>openapi.v3.Schema</code>
 */
class Schema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool nullable = 1;</code>
     */
    protected $nullable = false;
    /**
     * Generated from protobuf field <code>.openapi.v3.Discriminator discriminator = 2;</code>
     */
    protected $discriminator = null;
    /**
     * Generated from protobuf field <code>bool read_only = 3;</code>
     */
    protected $read_only = false;
    /**
     * Generated from protobuf field <code>bool write_only = 4;</code>
     */
    protected $write_only = false;
    /**
     * Generated from protobuf field <code>.openapi.v3.Xml xml = 5;</code>
     */
    protected $xml = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 6;</code>
     */
    protected $external_docs = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Any example = 7;</code>
     */
    protected $example = null;
    /**
     * Generated from protobuf field <code>bool deprecated = 8;</code>
     */
    protected $deprecated = false;
    /**
     * Generated from protobuf field <code>string title = 9;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>double multiple_of = 10;</code>
     */
    protected $multiple_of = 0.0;
    /**
     * Generated from protobuf field <code>double maximum = 11;</code>
     */
    protected $maximum = 0.0;
    /**
     * Generated from protobuf field <code>bool exclusive_maximum = 12;</code>
     */
    protected $exclusive_maximum = false;
    /**
     * Generated from protobuf field <code>double minimum = 13;</code>
     */
    protected $minimum = 0.0;
    /**
     * Generated from protobuf field <code>bool exclusive_minimum = 14;</code>
     */
    protected $exclusive_minimum = false;
    /**
     * Generated from protobuf field <code>int64 max_length = 15;</code>
     */
    protected $max_length = 0;
    /**
     * Generated from protobuf field <code>int64 min_length = 16;</code>
     */
    protected $min_length = 0;
    /**
     * Generated from protobuf field <code>string pattern = 17;</code>
     */
    protected $pattern = '';
    /**
     * Generated from protobuf field <code>int64 max_items = 18;</code>
     */
    protected $max_items = 0;
    /**
     * Generated from protobuf field <code>int64 min_items = 19;</code>
     */
    protected $min_items = 0;
    /**
     * Generated from protobuf field <code>bool unique_items = 20;</code>
     */
    protected $unique_items = false;
    /**
     * Generated from protobuf field <code>int64 max_properties = 21;</code>
     */
    protected $max_properties = 0;
    /**
     * Generated from protobuf field <code>int64 min_properties = 22;</code>
     */
    protected $min_properties = 0;
    /**
     * Generated from protobuf field <code>repeated string required = 23;</code>
     */
    private $required;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Any enum = 24;</code>
     */
    private $enum;
    /**
     * Generated from protobuf field <code>string type = 25;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference all_of = 26;</code>
     */
    private $all_of;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference one_of = 27;</code>
     */
    private $one_of;
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference any_of = 28;</code>
     */
    private $any_of;
    /**
     * Generated from protobuf field <code>.openapi.v3.Schema not = 29;</code>
     */
    protected $not = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.ItemsItem items = 30;</code>
     */
    protected $items = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.Properties properties = 31;</code>
     */
    protected $properties = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.AdditionalPropertiesItem additional_properties = 32;</code>
     */
    protected $additional_properties = null;
    /**
     * Generated from protobuf field <code>.openapi.v3.DefaultType default = 33;</code>
     */
    protected $default = null;
    /**
     * Generated from protobuf field <code>string description = 34;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string format = 35;</code>
     */
    protected $format = '';
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 36;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $nullable
     *     @type \Openapi\V3\Discriminator $discriminator
     *     @type bool $read_only
     *     @type bool $write_only
     *     @type \Openapi\V3\Xml $xml
     *     @type \Openapi\V3\ExternalDocs $external_docs
     *     @type \Openapi\V3\Any $example
     *     @type bool $deprecated
     *     @type string $title
     *     @type float $multiple_of
     *     @type float $maximum
     *     @type bool $exclusive_maximum
     *     @type float $minimum
     *     @type bool $exclusive_minimum
     *     @type int|string $max_length
     *     @type int|string $min_length
     *     @type string $pattern
     *     @type int|string $max_items
     *     @type int|string $min_items
     *     @type bool $unique_items
     *     @type int|string $max_properties
     *     @type int|string $min_properties
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $required
     *     @type array<\Openapi\V3\Any>|\Google\Protobuf\Internal\RepeatedField $enum
     *     @type string $type
     *     @type array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $all_of
     *     @type array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $one_of
     *     @type array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $any_of
     *     @type \Openapi\V3\Schema $not
     *     @type \Openapi\V3\ItemsItem $items
     *     @type \Openapi\V3\Properties $properties
     *     @type \Openapi\V3\AdditionalPropertiesItem $additional_properties
     *     @type \Openapi\V3\DefaultType $default
     *     @type string $description
     *     @type string $format
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool nullable = 1;</code>
     * @return bool
     */
    public function getNullable()
    {
        return $this->nullable;
    }

    /**
     * Generated from protobuf field <code>bool nullable = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullable($var)
    {
        GPBUtil::checkBool($var);
        $this->nullable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Discriminator discriminator = 2;</code>
     * @return \Openapi\V3\Discriminator|null
     */
    public function getDiscriminator()
    {
        return $this->discriminator;
    }

    public function hasDiscriminator()
    {
        return isset($this->discriminator);
    }

    public function clearDiscriminator()
    {
        unset($this->discriminator);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Discriminator discriminator = 2;</code>
     * @param \Openapi\V3\Discriminator $var
     * @return $this
     */
    public function setDiscriminator($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Discriminator::class);
        $this->discriminator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 3;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->read_only;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->read_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool write_only = 4;</code>
     * @return bool
     */
    public function getWriteOnly()
    {
        return $this->write_only;
    }

    /**
     * Generated from protobuf field <code>bool write_only = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setWriteOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->write_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Xml xml = 5;</code>
     * @return \Openapi\V3\Xml|null
     */
    public function getXml()
    {
        return $this->xml;
    }

    public function hasXml()
    {
        return isset($this->xml);
    }

    public function clearXml()
    {
        unset($this->xml);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Xml xml = 5;</code>
     * @param \Openapi\V3\Xml $var
     * @return $this
     */
    public function setXml($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Xml::class);
        $this->xml = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 6;</code>
     * @return \Openapi\V3\ExternalDocs|null
     */
    public function getExternalDocs()
    {
        return $this->external_docs;
    }

    public function hasExternalDocs()
    {
        return isset($this->external_docs);
    }

    public function clearExternalDocs()
    {
        unset($this->external_docs);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ExternalDocs external_docs = 6;</code>
     * @param \Openapi\V3\ExternalDocs $var
     * @return $this
     */
    public function setExternalDocs($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ExternalDocs::class);
        $this->external_docs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Any example = 7;</code>
     * @return \Openapi\V3\Any|null
     */
    public function getExample()
    {
        return $this->example;
    }

    public function hasExample()
    {
        return isset($this->example);
    }

    public function clearExample()
    {
        unset($this->example);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Any example = 7;</code>
     * @param \Openapi\V3\Any $var
     * @return $this
     */
    public function setExample($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Any::class);
        $this->example = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deprecated = 8;</code>
     * @return bool
     */
    public function getDeprecated()
    {
        return $this->deprecated;
    }

    /**
     * Generated from protobuf field <code>bool deprecated = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeprecated($var)
    {
        GPBUtil::checkBool($var);
        $this->deprecated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 9;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double multiple_of = 10;</code>
     * @return float
     */
    public function getMultipleOf()
    {
        return $this->multiple_of;
    }

    /**
     * Generated from protobuf field <code>double multiple_of = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setMultipleOf($var)
    {
        GPBUtil::checkDouble($var);
        $this->multiple_of = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double maximum = 11;</code>
     * @return float
     */
    public function getMaximum()
    {
        return $this->maximum;
    }

    /**
     * Generated from protobuf field <code>double maximum = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setMaximum($var)
    {
        GPBUtil::checkDouble($var);
        $this->maximum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool exclusive_maximum = 12;</code>
     * @return bool
     */
    public function getExclusiveMaximum()
    {
        return $this->exclusive_maximum;
    }

    /**
     * Generated from protobuf field <code>bool exclusive_maximum = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setExclusiveMaximum($var)
    {
        GPBUtil::checkBool($var);
        $this->exclusive_maximum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double minimum = 13;</code>
     * @return float
     */
    public function getMinimum()
    {
        return $this->minimum;
    }

    /**
     * Generated from protobuf field <code>double minimum = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setMinimum($var)
    {
        GPBUtil::checkDouble($var);
        $this->minimum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool exclusive_minimum = 14;</code>
     * @return bool
     */
    public function getExclusiveMinimum()
    {
        return $this->exclusive_minimum;
    }

    /**
     * Generated from protobuf field <code>bool exclusive_minimum = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setExclusiveMinimum($var)
    {
        GPBUtil::checkBool($var);
        $this->exclusive_minimum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_length = 15;</code>
     * @return int|string
     */
    public function getMaxLength()
    {
        return $this->max_length;
    }

    /**
     * Generated from protobuf field <code>int64 max_length = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 min_length = 16;</code>
     * @return int|string
     */
    public function getMinLength()
    {
        return $this->min_length;
    }

    /**
     * Generated from protobuf field <code>int64 min_length = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pattern = 17;</code>
     * @return string
     */
    public function getPattern()
    {
        return $this->pattern;
    }

    /**
     * Generated from protobuf field <code>string pattern = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->pattern = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_items = 18;</code>
     * @return int|string
     */
    public function getMaxItems()
    {
        return $this->max_items;
    }

    /**
     * Generated from protobuf field <code>int64 max_items = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxItems($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 min_items = 19;</code>
     * @return int|string
     */
    public function getMinItems()
    {
        return $this->min_items;
    }

    /**
     * Generated from protobuf field <code>int64 min_items = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinItems($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool unique_items = 20;</code>
     * @return bool
     */
    public function getUniqueItems()
    {
        return $this->unique_items;
    }

    /**
     * Generated from protobuf field <code>bool unique_items = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setUniqueItems($var)
    {
        GPBUtil::checkBool($var);
        $this->unique_items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_properties = 21;</code>
     * @return int|string
     */
    public function getMaxProperties()
    {
        return $this->max_properties;
    }

    /**
     * Generated from protobuf field <code>int64 max_properties = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxProperties($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 min_properties = 22;</code>
     * @return int|string
     */
    public function getMinProperties()
    {
        return $this->min_properties;
    }

    /**
     * Generated from protobuf field <code>int64 min_properties = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinProperties($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string required = 23;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * Generated from protobuf field <code>repeated string required = 23;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequired($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->required = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Any enum = 24;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEnum()
    {
        return $this->enum;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.Any enum = 24;</code>
     * @param array<\Openapi\V3\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEnum($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\Any::class);
        $this->enum = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 25;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference all_of = 26;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllOf()
    {
        return $this->all_of;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference all_of = 26;</code>
     * @param array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllOf($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\SchemaOrReference::class);
        $this->all_of = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference one_of = 27;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOneOf()
    {
        return $this->one_of;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference one_of = 27;</code>
     * @param array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOneOf($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\SchemaOrReference::class);
        $this->one_of = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference any_of = 28;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnyOf()
    {
        return $this->any_of;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.SchemaOrReference any_of = 28;</code>
     * @param array<\Openapi\V3\SchemaOrReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnyOf($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\SchemaOrReference::class);
        $this->any_of = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Schema not = 29;</code>
     * @return \Openapi\V3\Schema|null
     */
    public function getNot()
    {
        return $this->not;
    }

    public function hasNot()
    {
        return isset($this->not);
    }

    public function clearNot()
    {
        unset($this->not);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Schema not = 29;</code>
     * @param \Openapi\V3\Schema $var
     * @return $this
     */
    public function setNot($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Schema::class);
        $this->not = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ItemsItem items = 30;</code>
     * @return \Openapi\V3\ItemsItem|null
     */
    public function getItems()
    {
        return $this->items;
    }

    public function hasItems()
    {
        return isset($this->items);
    }

    public function clearItems()
    {
        unset($this->items);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.ItemsItem items = 30;</code>
     * @param \Openapi\V3\ItemsItem $var
     * @return $this
     */
    public function setItems($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\ItemsItem::class);
        $this->items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Properties properties = 31;</code>
     * @return \Openapi\V3\Properties|null
     */
    public function getProperties()
    {
        return $this->properties;
    }

    public function hasProperties()
    {
        return isset($this->properties);
    }

    public function clearProperties()
    {
        unset($this->properties);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.Properties properties = 31;</code>
     * @param \Openapi\V3\Properties $var
     * @return $this
     */
    public function setProperties($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\Properties::class);
        $this->properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.AdditionalPropertiesItem additional_properties = 32;</code>
     * @return \Openapi\V3\AdditionalPropertiesItem|null
     */
    public function getAdditionalProperties()
    {
        return $this->additional_properties;
    }

    public function hasAdditionalProperties()
    {
        return isset($this->additional_properties);
    }

    public function clearAdditionalProperties()
    {
        unset($this->additional_properties);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.AdditionalPropertiesItem additional_properties = 32;</code>
     * @param \Openapi\V3\AdditionalPropertiesItem $var
     * @return $this
     */
    public function setAdditionalProperties($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\AdditionalPropertiesItem::class);
        $this->additional_properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.DefaultType default = 33;</code>
     * @return \Openapi\V3\DefaultType|null
     */
    public function getDefault()
    {
        return $this->default;
    }

    public function hasDefault()
    {
        return isset($this->default);
    }

    public function clearDefault()
    {
        unset($this->default);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.DefaultType default = 33;</code>
     * @param \Openapi\V3\DefaultType $var
     * @return $this
     */
    public function setDefault($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\DefaultType::class);
        $this->default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 34;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string format = 35;</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>string format = 35;</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 36;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 36;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

