<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter or as a query parameter), mutual TLS (use of a client certificate), OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and OpenID Connect.   Please note that currently (2019) the implicit flow is about to be deprecated OAuth 2.0 Security Best Current Practice. Recommended for most use case is Authorization Code Grant flow with PKCE.
 *
 * Generated from protobuf message <code>openapi.v3.SecurityScheme</code>
 */
class SecurityScheme extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string in = 4;</code>
     */
    protected $in = '';
    /**
     * Generated from protobuf field <code>string scheme = 5;</code>
     */
    protected $scheme = '';
    /**
     * Generated from protobuf field <code>string bearer_format = 6;</code>
     */
    protected $bearer_format = '';
    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlows flows = 7;</code>
     */
    protected $flows = null;
    /**
     * Generated from protobuf field <code>string open_id_connect_url = 8;</code>
     */
    protected $open_id_connect_url = '';
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 9;</code>
     */
    private $specification_extension;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $description
     *     @type string $name
     *     @type string $in
     *     @type string $scheme
     *     @type string $bearer_format
     *     @type \Openapi\V3\OauthFlows $flows
     *     @type string $open_id_connect_url
     *     @type array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $specification_extension
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string in = 4;</code>
     * @return string
     */
    public function getIn()
    {
        return $this->in;
    }

    /**
     * Generated from protobuf field <code>string in = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIn($var)
    {
        GPBUtil::checkString($var, True);
        $this->in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scheme = 5;</code>
     * @return string
     */
    public function getScheme()
    {
        return $this->scheme;
    }

    /**
     * Generated from protobuf field <code>string scheme = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setScheme($var)
    {
        GPBUtil::checkString($var, True);
        $this->scheme = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bearer_format = 6;</code>
     * @return string
     */
    public function getBearerFormat()
    {
        return $this->bearer_format;
    }

    /**
     * Generated from protobuf field <code>string bearer_format = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBearerFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->bearer_format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlows flows = 7;</code>
     * @return \Openapi\V3\OauthFlows|null
     */
    public function getFlows()
    {
        return $this->flows;
    }

    public function hasFlows()
    {
        return isset($this->flows);
    }

    public function clearFlows()
    {
        unset($this->flows);
    }

    /**
     * Generated from protobuf field <code>.openapi.v3.OauthFlows flows = 7;</code>
     * @param \Openapi\V3\OauthFlows $var
     * @return $this
     */
    public function setFlows($var)
    {
        GPBUtil::checkMessage($var, \Openapi\V3\OauthFlows::class);
        $this->flows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string open_id_connect_url = 8;</code>
     * @return string
     */
    public function getOpenIdConnectUrl()
    {
        return $this->open_id_connect_url;
    }

    /**
     * Generated from protobuf field <code>string open_id_connect_url = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenIdConnectUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_id_connect_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificationExtension()
    {
        return $this->specification_extension;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedAny specification_extension = 9;</code>
     * @param array<\Openapi\V3\NamedAny>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificationExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedAny::class);
        $this->specification_extension = $arr;

        return $this;
    }

}

