<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/openapi.proto

namespace Openapi\V3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Lists the required security schemes to execute this operation. The name used for each property MUST correspond to a security scheme declared in the Security Schemes under the Components Object.  Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where multiple query parameters or HTTP headers are required to convey security information.  When a list of Security Requirement Objects is defined on the OpenAPI Object or Operation Object, only one of the Security Requirement Objects in the list needs to be satisfied to authorize the request.
 *
 * Generated from protobuf message <code>openapi.v3.SecurityRequirement</code>
 */
class SecurityRequirement extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedStringArray additional_properties = 1;</code>
     */
    private $additional_properties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Openapi\V3\NamedStringArray>|\Google\Protobuf\Internal\RepeatedField $additional_properties
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedStringArray additional_properties = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdditionalProperties()
    {
        return $this->additional_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .openapi.v3.NamedStringArray additional_properties = 1;</code>
     * @param array<\Openapi\V3\NamedStringArray>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdditionalProperties($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openapi\V3\NamedStringArray::class);
        $this->additional_properties = $arr;

        return $this;
    }

}

