<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/v1/users.proto

namespace Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>users.CheckEmailResponse</code>
 */
class CheckEmailResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_unique = 1;</code>
     */
    protected $is_unique = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_unique
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users\V1\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_unique = 1;</code>
     * @return bool
     */
    public function getIsUnique()
    {
        return $this->is_unique;
    }

    /**
     * Generated from protobuf field <code>bool is_unique = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsUnique($var)
    {
        GPBUtil::checkBool($var);
        $this->is_unique = $var;

        return $this;
    }

}

