<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/v1/users.proto

namespace Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>users.LogoutResponse</code>
 */
class LogoutResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users\V1\Users::initOnce();
        parent::__construct($data);
    }

}

