<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/v1/users.proto

namespace GPBMetadata\Users\V1;

class Users
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
¬
users/v1/users.protousers"{
SignUpRequest
email (	
password (	

first_name (	
	last_name (	
role_id (	
	role_name (	"R
SignUpResponse

id (	
email (	

first_name (	
	last_name (	"0
SignInRequest
email (	
password (	"a
SignInResponse
token (	

id (	
email (	

first_name (	
	last_name (	"
	MeRequest
token (	"r

MeResponse

id (	
email (	

first_name (	
	last_name (	
role_id (	
	role_name (	"
LogoutRequest
token (	"
LogoutResponse""
CheckEmailRequest
email (	"\'
CheckEmailResponse
	is_unique (2Ñ
UserServiceA

CheckEmail.users.CheckEmailRequest.users.CheckEmailResponseO
SignUp.users.SignUpRequest.users.SignUpResponse"Ç”‰ì/v1/users/signupO
SignIn.users.SignInRequest.users.SignInResponse"Ç”‰ì/v1/users/signin?
Me.users.MeRequest.users.MeResponse"Ç”‰ì/v1/users/meO
Logout.users.LogoutRequest.users.LogoutResponse"Ç”‰ì/v1/users/logoutBZonboardingservice/users/v1;v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

