---
# example https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml

# Lint directives.
lint:
  rules:
    # The specific linters to remove.
    remove:
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_FIELD_NAMES_PREFIX

  # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 120
