<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health/v1/health.proto

namespace GPBMetadata\Health\V1;

class Health
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(
            '
é
health/v1/health.proto	health.v1google/protobuf/empty.proto"L

CheckReply
status (	
version (	
env (	
postgres (	2T
HealthJ
Check.google.protobuf.Empty.health.v1.CheckReply"Ç”‰ì
/v1/healthB Zonboardingservice/health/v1;v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

