<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi/v3/annotations.proto

namespace GPBMetadata\Openapi\V3;

class Annotations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Openapi\V3\Openapi::initOnce();
        $pool->internalAddGeneratedFile(
            '
°
openapi/v3/annotations.proto
openapi.v3 google/protobuf/descriptor.protoBZ
org.openapi_v3BAnnotationsProtoPZ.github.com/google/gnostic/openapiv3;openapi_v3¢OASbproto3'
        , true);

        static::$is_initialized = true;
    }
}

